# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views/calculo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculo(object):
    def setupUi(self, calculo):
        calculo.setObjectName("calculo")
        calculo.resize(830, 530)
        self.horizontalLayout = QtWidgets.QHBoxLayout(calculo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(calculo)
        self.widget.setStyleSheet("font: 15pt \"Courier\";")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(calculo)
        self.widget_2.setStyleSheet("font: 15pt \"Courier\";")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEquacao = QtWidgets.QLineEdit(self.widget_2)
        self.lineEquacao.setObjectName("lineEquacao")
        self.verticalLayout_2.addWidget(self.lineEquacao)
        self.lineX = QtWidgets.QLineEdit(self.widget_2)
        self.lineX.setObjectName("lineX")
        self.verticalLayout_2.addWidget(self.lineX)
        self.lineY = QtWidgets.QLineEdit(self.widget_2)
        self.lineY.setObjectName("lineY")
        self.verticalLayout_2.addWidget(self.lineY)
        self.linePasso = QtWidgets.QLineEdit(self.widget_2)
        self.linePasso.setObjectName("linePasso")
        self.verticalLayout_2.addWidget(self.linePasso)
        self.lineRepeticao = QtWidgets.QLineEdit(self.widget_2)
        self.lineRepeticao.setObjectName("lineRepeticao")
        self.verticalLayout_2.addWidget(self.lineRepeticao)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(calculo)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonCalcular = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.buttonCalcular.sizePolicy().hasHeightForWidth())
        self.buttonCalcular.setSizePolicy(sizePolicy)
        self.buttonCalcular.setStyleSheet("font: 20pt \"Courier\";\n"
"background: rgb(132, 132, 132)")
        self.buttonCalcular.setObjectName("buttonCalcular")
        self.verticalLayout_3.addWidget(self.buttonCalcular)
        self.buttonLimpar = QtWidgets.QPushButton(self.widget_3)
        self.buttonLimpar.setStyleSheet("font: 20pt \"Courier\";\n"
"background: rgb(132, 132, 132)")
        self.buttonLimpar.setObjectName("buttonLimpar")
        self.verticalLayout_3.addWidget(self.buttonLimpar)
        self.horizontalLayout.addWidget(self.widget_3)

        self.retranslateUi(calculo)
        QtCore.QMetaObject.connectSlotsByName(calculo)

    def retranslateUi(self, calculo):
        _translate = QtCore.QCoreApplication.translate
        calculo.setWindowTitle(_translate("calculo", "Form"))
        self.label.setText(_translate("calculo", "Equação"))
        self.label_3.setText(_translate("calculo", "x0"))
        self.label_2.setText(_translate("calculo", "y0"))
        self.label_4.setText(_translate("calculo", "Passo(h)"))
        self.label_5.setText(_translate("calculo", "Repetições"))
        self.buttonCalcular.setText(_translate("calculo", "Calcular"))
        self.buttonLimpar.setText(_translate("calculo", "Limpar"))
