# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views/grafico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grafico(object):
    def setupUi(self, grafico):
        grafico.setObjectName("grafico")
        grafico.resize(830, 530)
        self.widgetgrafico = QtWidgets.QWidget(grafico)
        self.widgetgrafico.setGeometry(QtCore.QRect(0, 0, 830, 530))
        self.widgetgrafico.setObjectName("widgetgrafico")

        self.retranslateUi(grafico)
        QtCore.QMetaObject.connectSlotsByName(grafico)

    def retranslateUi(self, grafico):
        _translate = QtCore.QCoreApplication.translate
        grafico.setWindowTitle(_translate("grafico", "Form"))
