# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views/sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sobre(object):
    def setupUi(self, sobre):
        sobre.setObjectName("sobre")
        sobre.resize(830, 530)
        self.widget = QtWidgets.QWidget(sobre)
        self.widget.setGeometry(QtCore.QRect(0, 0, 830, 530))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout.addWidget(self.textBrowser_3)

        self.retranslateUi(sobre)
        QtCore.QMetaObject.connectSlotsByName(sobre)

    def retranslateUi(self, sobre):
        _translate = QtCore.QCoreApplication.translate
        sobre.setWindowTitle(_translate("sobre", "Form"))
        self.textBrowser.setHtml(_translate("sobre", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Runge-Kutta</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    </span><span style=\" font-size:12pt;\">O método de Runge-Kutta é uma família de algoritmos numéricos utilizados para resolver equações diferenciais ordinárias (EDOs). Ele é especialmente adequado para resolver EDOs que não têm solução analítica simples ou quando a solução analítica é difícil de obter. O método de Runge-Kutta é amplamente usado em diversas áreas da ciência, engenharia e computação para simulações e modelagem de sistemas dinâmicos.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">    A ideia geral por trás do método de Runge-Kutta é aproximar a solução de uma EDO em incrementos discretos, calculando o valor da função em pontos intermediários entre o início e o fim do intervalo desejado. A forma mais comum do método é o Runge-Kutta de quarta ordem (RK4), mas existem variantes com diferentes ordens de precisão.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("sobre", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Valores Iniciais</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Equação: </span><span style=\" font-size:12pt;\">Comece com uma equação diferencial ordinária que você deseja resolver, por exemplo: dy/dx = f(x, y).</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">y0</span><span style=\" font-size:12pt;\">: O valor y0​ é o valor inicial da função que você está tentando resolver. Ele representa a solução da EDO no ponto inicial x0​.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">x0</span><span style=\" font-size:12pt;\">: O valor x0​ é o ponto inicial do intervalo de integração. Ele define o ponto a partir do qual você começa a resolver a EDO</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Passo(h)</span><span style=\" font-size:12pt;\">: Escolha um passo de integração h, que é o tamanho do incremento entre os pontos de x. Quanto menor o valor de h, mais preciso será o resultado, mas também pode aumentar o custo computacional.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Repetição</span><span style=\" font-size:12pt;\">: A iteração é o processo central no método de Runge-Kutta e é usada para calcular os valores intermediários de uma função ao longo do intervalo de integração.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
