# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views/tabela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabela(object):
    def setupUi(self, tabela):
        tabela.setObjectName("tabela")
        tabela.resize(830, 530)
        self.tableWidget = QtWidgets.QTableWidget(tabela)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 830, 530))
        self.tableWidget.setStyleSheet("font: 16pt \"Arial\";")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(415)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(415)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)

        self.retranslateUi(tabela)
        QtCore.QMetaObject.connectSlotsByName(tabela)

    def retranslateUi(self, tabela):
        _translate = QtCore.QCoreApplication.translate
        tabela.setWindowTitle(_translate("tabela", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tabela", "X"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("tabela", "y"))
